// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjpvnbjymbodrxbqlynw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqcHZuYmp5bWJvZHJ4YnFseW53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NzYxNjQsImV4cCI6MjA2NTA1MjE2NH0.GZKhRavCxI2qrpFg0vQ65pfqWad5NGwZUyiKJQvgrew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);